### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by BigT2013** [SamuelSVD/TrayDir#234]
Setting off Virus scanner. Says it's a Trojan. Please advise, Thank you.

**Comment by SamuelSVD** [comment]
Unfortunately TrayDir has been getting incorrectly flagged as a virus. It has to do with how Plugins work. They allow a user to create scripts. For more info see the following issue:

https://github.com/SamuelSVD/TrayDir/issues/190

If you would like to try out TrayDir without plugins you can try TrayDir Lite.

https://github.com/SamuelSVD/TrayDir-Lite/releases/tag/v3.4.0
